Project_63131717/Areas/Admin_63131717/Controllers/QLSach_63131717Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project_63131717.Models;
using PagedList;
using Project_63131717.Security;

namespace Project_63131717.Areas.Admin_63131717
{
    public class QLSach_63131717Controller : CheckLogin_63131717Controller
    {
        private Project_63131717Entities db = new Project_63131717Entities();
        private const int PageSize = 10;

        // GET: Admin_63131717/QL_Sach_63131717
        public ActionResult Index(int? page, string searchDropdown, string searchInput)
        {
            var saches = db.Saches.Include(s => s.TheLoai).ToList();
            int pageNumber = (page ?? 1);

            if (!string.IsNullOrEmpty(searchInput))
            {
                switch (searchDropdown)
                {
                    case "tenSach":
                        saches = saches.Where(s => s.TenSach.Contains(searchInput)).ToList();
                        ViewBag.tenSach = searchInput;
                        break;

                    case "theLoai":
                        saches = saches.Where(s => s.TheLoai.TenTheLoai.Contains(searchInput)).ToList();
                        ViewBag.theLoai = searchInput;
                        break;

                    case "tacGia":
                        saches = saches.Where(s => s.TacGia.Contains(searchInput)).ToList();
                        ViewBag.tacGia = searchInput;
                        break;
                }
            }

            ViewBag.searchDropdown = searchDropdown;
            ViewBag.searchInput = searchInput;

            return View(saches.ToPagedList(pageNumber, PageSize));
        }




    // GET: Admin_63131717/QL_Sach_63131717/Details/5
    public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // GET: Admin_63131717/QL_Sach_63131717/Create
        public ActionResult Create()
        {
            ViewBag.IDTheLoai = new SelectList(db.TheLoais, "IDTheLoai", "TenTheLoai");
            return View();
        }

        // POST: Admin_63131717/QLSach_63131717/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDSach,TenSach,IDTheLoai,MoTa,TacGia,NgayXuatBan,SoLuong,HinhAnh")] Sach sach)
        {
            var existing = db.Saches.Find(sach.IDSach);
            if (existing != null)
            {
                return Content("ID đã tồn tại. Vui lòng chọn ID khác.");
            }
            // Kiểm tra xem đó có phải là yêu cầu POST hay không
            if (Request.HttpMethod == "POST")
            {
                var img = Request.Files["Avatar"];
                string postedFileName = System.IO.Path.GetFileName(img.FileName);
                // Lưu hình đại diện về Server
                var path = Server.MapPath("/Areas/Admin_63131717/Images/" + postedFileName);
                img.SaveAs(path);
                sach.HinhAnh = postedFileName;
                if (ModelState.IsValid)
                {
                    db.Saches.Add(sach);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            // Nếu đó không phải là một yêu cầu POST hoặc nếu có lỗi ModelState, hiển thị biểu mẫu
            ViewBag.IDTheLoai = new SelectList(db.TheLoais, "IDTheLoai", "TenTheLoai", sach.IDTheLoai);
            return View(sach);
        }




        // GET: Admin_63131717/QL_Sach_63131717/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDTheLoai = new SelectList(db.TheLoais, "IDTheLoai", "TenTheLoai", sach.IDTheLoai);
            return View(sach);
        }

        // POST: Admin_63131717/QL_Sach_63131717/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDSach,TenSach,IDTheLoai,MoTa,TacGia,NgayXuatBan,SoLuong,HinhAnh")] Sach sach)
        {
            if (Request.HttpMethod == "POST")
            {
                var img = Request.Files["Avatar"];

                if (img != null && img.ContentLength > 0)
                {
                    string postedFileName = System.IO.Path.GetFileName(img.FileName);
                    // Lưu hình đại diện về Server
                    var path = Server.MapPath("/Areas/Admin_63131717/Images/" + postedFileName);
                    img.SaveAs(path);
                    sach.HinhAnh = postedFileName;

                    if (ModelState.IsValid)
                    {
                        db.Entry(sach).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
            }

            // Nếu có lỗi ModelState hoặc không có tệp hình ảnh được chọn, hiển thị biểu mẫu chỉ đọc
            ViewBag.IDTheLoai = new SelectList(db.TheLoais, "IDTheLoai", "TenTheLoai", sach.IDTheLoai);
            return View(sach);
        }
        
        // GET: Admin_63131717/QL_Sach_63131717/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // POST: Admin_63131717/QL_Sach_63131717/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sach sach = db.Saches.Find(id);
            db.Saches.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project_63131717/Areas/Admin_63131717/Views/QLSach_63131717/Create.cshtml
@model Project_63131717.Models.Sach

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin_63131717/Views/Shared/PageAdmin.cshtml";
}

<style>
    body {
        background: #f5e7e7
    }
    /* Định dạng tổng thể cho form */
    .form-horizontal {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    /* Định dạng cho tiêu đề */
    h4 {
        text-align: center;
        font-weight: 700;
    }

    /* Định dạng cho nhãn và input */
    .form-group {
        margin-bottom: 20px;
    }

    .control-label {
        font-weight: bold;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    /* Định dạng cho nút Lưu */
    input[type="submit"] {
        background-color: #3498db;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        input[type="submit"]:hover {
            background-color: #2575b7;
        }

    /* Định dạng cho thông báo lỗi */
    .text-danger {
        color: #ff6347;
    }

    input {
        margin-top: 10px
    }

    a {
        text-decoration: none
    }

    .btn-back {
        background-color: #007bff;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        display: inline-block;
        margin-left: 15px;
    }

        .btn-back:hover, .btn-delete:hover {
            background-color: #0056b3;
        }


    .btn-delete {
        background-color: #007bff !important;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        display: inline-block;
        margin: 0;
        margin-right: 15px;

    }
    input, textarea {
        margin: 10px 0;
    }

    textarea {
        width: 100%;
        height: 120px;
    }
</style>

@using (Html.BeginForm("Create","QLSach_63131717",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4 style="color:blue" class="text-uppercase">Thêm Sách Mới</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.IDSach, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.IDSach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IDSach, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IDTheLoai, "Thể loại", htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-12">
            @Html.DropDownListFor(model => model.IDTheLoai, (SelectList)ViewBag.IDTheLoai, "-- Chọn thể loại--", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.IDTheLoai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TacGia, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayXuatBan, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.NgayXuatBan, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.NgayXuatBan, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-4" })
        <div class="col-md-12">
            <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group no-color d-flex justify-content-center align-items-center">
        <input type="submit" value="Tạo mới" class="btn btn-delete" /> |
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-back" })
    </div>
</div>
}

Project_63131717/Areas/Admin_63131717/Views/QLSach_63131717/Delete.cshtml
@model Project_63131717.Models.Sach

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin_63131717/Views/Shared/PageAdmin.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<style>
    body {
        background-color: #f8f9fa;
        margin: 0;
        padding: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
    }

    .details-container {
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
        width: 800px;
        max-width: 100%;
        text-align: center;
    }

    h2 {
        color: #007bff;
    }

    dl {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    dt, dd {
        flex: 0 0 48%;
        margin-bottom: 10px;
    }

    .btn-back {
        background-color: #007bff;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        display: inline-block;
        margin-left: 15px;
    }

        .btn-back:hover {
            background-color: #0056b3;
        }

    .btn-delete:hover {
        background: #8b0b0b;
        color: #fff
    }

    .btn-delete {
        background-color: red;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        display: inline-block;
        margin-right: 15px;
    }
    dd{
        text-align:start
    }
    dl{
        margin-left:25%;
        text-align:start
    }
</style>

<div class="details-container">
    <h2 class="text-danger">Bạn chắc chắn muốn sách này ?</h2>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TacGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayXuatBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayXuatBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TheLoai.TenTheLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TheLoai.TenTheLoai)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color d-flex justify-content-center align-items-center">
            <input type="submit" value="Xóa" class="btn btn-delete" /> |
            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-back" })
        </div>
    }
</div>

Project_63131717/Areas/Admin_63131717/Views/QLSach_63131717/Details.cshtml
@model Project_63131717.Models.Sach

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin_63131717/Views/Shared/PageAdmin.cshtml";
}

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<style>
    body {
        background-color: #f8f9fa;
        margin: 0;
        padding: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
    }

    .details-container {
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
        width: 800px;
        max-width: 100%;
        text-align: center;
    }

    h2 {
        color: #007bff;
    }

    dl {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    dt, dd {
        flex: 0 0 48%;
        margin-bottom: 10px;
    }

    .btn-back {
        background-color: #007bff;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        display: inline-block;
        margin-left: 15px;
    }

        .btn-back:hover {
            background-color: #0056b3;
        }
    dd {
        text-align: start
    }

    dl {
        margin-left: 25%;
        text-align: start
    }
</style>


<div class="details-container">
    <h2 style="margin-bottom:30px">Thông tin cuốn sách</h2>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TacGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TacGia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayXuatBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayXuatBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HinhAnh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HinhAnh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TheLoai.TenTheLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TheLoai.TenTheLoai)
        </dd>
    </dl>


    <div class="form-actions no-color d-flex justify-content-center align-items-center">
        @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-back" })
    </div>
</div>

Project_63131717/Areas/Admin_63131717/Views/QLSach_63131717/Edit.cshtml
@model Project_63131717.Models.Sach

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin_63131717/Views/Shared/PageAdmin.cshtml";
}

<style>
    body {
        background: #f5e7e7
    }
    a{text-decoration:none}
    /* Định dạng tổng thể cho form */
    .form-horizontal {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    /* Định dạng cho tiêu đề */
    h4 {
        text-align: center;
        font-weight: 700;
    }

    /* Định dạng cho nhãn và input */
    .form-group {
        margin-bottom: 20px;
    }

    .control-label {
        font-weight: bold;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    /* Định dạng cho nút Lưu */
    input[type="submit"], .submit a {
        background-color: #3498db;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        input[type="submit"]:hover, .submit a:hover {
            background-color: #2575b7;
        }

    /* Định dạng cho thông báo lỗi */
    .text-danger {
        color: #ff6347;
    }

    input ,textarea{
        margin: 10px 0;
    }
    textarea {
        width: 100%;
        height: 120px;
    }
</style>


@using (Html.BeginForm("Edit","QLSach_63131717",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 class="text-center text-uppercase" style="color:blue">Sửa thông tin cuốn sách</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDSach)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSach, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDTheLoai, "Thể loại", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.DropDownList("IDTheLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDTheLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TacGia, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayXuatBan, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.NgayXuatBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayXuatBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HinhAnh, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-12">
                <input type="file" style="height:30px;" name="Avatar" accept="image/*" />
                @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <img src="~/Areas/Admin_63131717/Images/@Model.HinhAnh" alt="Hình ảnh" width="100" height="100" />
            </div>
        </div>

        <div class="form-group submit">
            <div class="col-md-offset-2 col-md-12 d-flex justify-content-around align-items-center">
                <input style="margin:0;" type="submit" value="Lưu thay đổi" class="btn btn-default" />
                @Html.ActionLink("Quay lại", "Index")
            </div>
        </div>
    </div>
}

<div>
    
</div>