Project_63131717/Controllers/Login_63131717Controller.cs
using Project_63131717.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Project_63131717.Controllers
{
    public class Login_63131717Controller : Controller
    {
        Project_63131717Entities db = new Project_63131717Entities();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoginAcc(string NameUser, string Password)
        {
            // Kiểm tra người dùng thông thường
            var user = db.DocGias.SingleOrDefault(u => u.NameUser == NameUser && u.Password == Password);
            var admin = db.DangNhaps.SingleOrDefault(a => a.Username == NameUser && a.Password == Password);

            if (user != null)
            {
                // Đây là người dùng thường, chuyển hướng đến trang người dùng
                Session["NameUser"] = user.NameUser;
                return RedirectToAction("Index", "ListBook_63131717");
            }
            else if (admin != null)
            {
                // Đây là quản trị viên, chuyển hướng đến trang quản trị
                Session["NameUser"] = admin.Username;
                return RedirectToAction("Index", "QLSach_63131717", new { area = "Admin_63131717" });
            }
            else
            {
                return View("Index");
            }
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(DocGia user)
        {
                if (ModelState.IsValid)
                {
                    // Kiểm tra xem NameUser và Password có trùng nhau không
                    var existingUser = db.DocGias
                        .Where(u => u.NameUser == user.NameUser)
                        .FirstOrDefault();

                    if (existingUser != null)
                    {

                        ViewBag.ErrorRegister = "Tài khoản đã tồn tại. Vui lòng nhập thông tin khác.";
                        return View();
                    }

                    // Nếu không trùng, tiếp tục thêm người dùng mới vào cơ sở dữ liệu
                    db.DocGias.Add(user);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            return View();
        }
        public ActionResult LogOut()
        {
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home_63131717");
        }
    }
}

Project_63131717/Views/Login_63131717/Index.cshtml
@model Project_63131717.Models.DocGia
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="~/Content/material-icon/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/Content/css/style-lg.css">
    <style>
        a {
            text-decoration: none;
            color: black;
        }
    </style>
</head>
<body>
    @using (Html.BeginForm("LoginAcc", "Login_63131717", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <section class="sign-in">
            <div class="container">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="~/Content/Image/signin-image.jpg" alt="singin image"></figure>
                        <a href="~/Login_63131717/Register" class="signup-image-link">Tạo tài khoản mới</a>
                    </div>
                    <div class="signin-form">
                        <h2 class="form-title">ĐĂNG NHẬP</h2>
                        <form method="POST" class="register-form" id="login-form">
                            <div class="form-group">
                                <label for="NameUser"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="NameUser" id="NameUser" placeholder="Tài khoản" />
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="Password" id="Password" placeholder="Mật khẩu" />
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Nhớ tài khoản ?</label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" class="form-submit" style="background:#2429f7" value="Log in" />
                            </div>
                        </form>
                        <div class="social-login">
                            <span class="social-label">Or login with</span>
                            <ul class="socials">
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                                <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    }
    <script src="~/Content/jquery/jquery.min.js"></script>
    <script src="~/Content/main.js"></script>
</body>
</html>

Project_63131717/Views/Login_63131717/Register.cshtml
@model Project_63131717.Models.DocGia
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Register</title>
    <link rel="stylesheet" href="~/Content/material-icon/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/Content/css/style-lg.css">
    <style>
        a{
            text-decoration:none;
            color:black
        }
        .field-validation-error {
            color: red;
            padding-bottom:30px
        }
        .form-group{
            margin-bottom:10px
        }
        

    </style>
</head>
<body>
    @using (Html.BeginForm("Register", "Login_63131717", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <section class="signup">
            <div class="container">
                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">ĐĂNG KÍ</h2>
                        <div class="form-group">
                            <div class="form-group">
                                <label for="TenDG"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input class="form-control" type="text" name="TenDG" id="TenDG" placeholder="Tên của bạn" />
                            </div>
                            @Html.ValidationMessageFor(model => model.TenDG)
                        </div>
                        <div class="form-group">
                            <div class="form-group">
                                <label for="DienThoai"><i class="zmdi zmdi-phone"></i></label>
                                <input class="form-control" type="text" name="DienThoai" id="DienThoai" placeholder="Số điện thoại" />

                            </div>
                            @Html.ValidationMessageFor(model => model.DienThoai)
                        </div>

                        <div class="form-group">
                            <div class="form-group">
                                <label for="DiaChi"><i class="zmdi zmdi-account-calendar"></i></label>
                                <input class="form-control" type="text" name="DiaChi" id="DiaChi" placeholder="Địa chỉ" />

                            </div>
                            @Html.ValidationMessageFor(model => model.DiaChi)
                        </div>
                        
                        <div class="form-group">
                            <div class="form-group">
                                <label for="NameUser"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input class="form-control" type="email" name="NameUser" id="NameUser" placeholder="Tên tài khoản" />

                            </div>
                            @Html.ValidationMessageFor(model => model.NameUser)
                        </div>
                       
                        <div class="form-group">
                            <div class="form-group">
                                <label for="Password"><i class="zmdi zmdi-lock"></i></label>
                                <input class="form-control" type="password" name="Password" id="Password" placeholder="Mật khẩu" />

                            </div>
                            @Html.ValidationMessageFor(model => model.Password)
                        </div>
                        
                        <div class="form-group">
                            <input class="form-control agree-term" type="checkbox" name="agree-term" id="agree-term" />
                            <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                        </div>
                        <div class="form-group form-button">
                            <input class="form-control form-submit" type="submit" style="background:#2429f7" value="Register" />
                        </div>
                        <div class="error text-danger mt-3">
                            @ViewBag.ErrorRegister
                        </div>
                    </div>
                        <div class="signup-image">
                            <figure><img src="~/Content/Image/signup-image.jpg" alt="sing up image"></figure>
                            <a href="~/Login_63131717/Index" class="signup-image-link">Tôi đã có tài khoản ?</a>
                        </div>
                    </div>
            </div>
        </section>
    }
    <script src="~/Content/jquery/jquery.min.js"></script>
    <script src="~/Content/main.js"></script>
</body>
</html>