Project_63131717/Areas/Admin_63131717/Controllers/QLPhieuMuon_63131717Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using PagedList;
using Project_63131717.Models;
using Project_63131717.Security;

namespace Project_63131717.Areas.Admin_63131717.Controllers
{
    public class QLPhieuMuon_63131717Controller : CheckLogin_63131717Controller
    {
        private Project_63131717Entities db = new Project_63131717Entities();
        private const int pageSize = 10;

        // GET: Admin_63131717/QLPhieuMuon_63131717
        public ActionResult Index(int? page)
        {
            var pm = db.PhieuMuons.ToList();
            int pageNumber = (page ?? 1);
            return View(pm.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult Edit(int id)
        {
            return View(db.PhieuMuons.Where(s => s.IDPM == id).FirstOrDefault());
        }


        [HttpPost]
        public ActionResult Edit([Bind(Include = "IDPM,IDDG,NgayMuon,NgayTra,TienPhat,GhiChu")] PhieuMuon p)
        {

            // TODO: Add update logic here
            if (ModelState.IsValid)
            {
                db.Entry(p).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();

        }


        public ActionResult Phat(int id)
        {
            return View(db.PhieuMuons.Where(s => s.IDPM == id).FirstOrDefault());
        }


        [HttpPost]
        public ActionResult Phat([Bind(Include = "IDPM,IDDG,NgayMuon,NgayTra,TienPhat,GhiChu")] PhieuMuon p)
        {

            if (ModelState.IsValid)
            {
                db.Entry(p).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();

        }


        public ActionResult Delete(int id)
        {
            return View(db.PhieuMuons.Where(s => s.IDPM == id).FirstOrDefault());
        }


        [HttpPost]
        public ActionResult Delete(int id, PhieuMuon p)
        {
            try
            {

                p = db.PhieuMuons.Where(s => s.IDPM == id).FirstOrDefault();
                if (p.TienPhat != 0)
                {
                    return Content("Độc giả chưa đóng tiền phạt thì không được xóa phiếu mượn!'");
                }
                db.PhieuMuons.Remove(p);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Bạn Không được xóa! Sách vẫn chưa được trả vui lòng kiểm tra lại.....");
            }
        }
    }
}

Project_63131717/Areas/Admin_63131717/Views/QLPhieuMuon_63131717/Delete.cshtml
@model Project_63131717.Models.PhieuMuon

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin_63131717/Views/Shared/PageAdmin.cshtml";
}

<link href="~/Content/bootstrap.css" rel="stylesheet" />
<style>
    body {
        background-color: #f8f9fa;
        margin: 0;
        padding: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100vh;
    }

    .details-container {
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 20px;
        width: 800px;
        max-width: 100%;
        text-align: center;
    }

    h2 {
        color: #007bff;
    }

    dl {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    dt, dd {
        flex: 0 0 48%;
        margin-bottom: 10px;
    }

    .btn-back {
        background-color: #007bff;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        display: inline-block;
        margin-left: 15px;
    }

        .btn-back:hover {
            background-color: #0056b3;
        }

    .btn-delete:hover {
        background: #8b0b0b;
        color: #fff
    }

    .btn-delete {
        background-color: red;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        text-decoration: none;
        display: inline-block;
        margin-right: 15px;
    }

    dd {
        text-align: start
    }

    dl {
        margin-left: 25%;
        text-align: start
    }
</style>

<div class="details-container">
    <h2 class="text-danger text-uppercase mb-4">Bạn chắc chắn muốn xóa phiếu này ?</h2>

    <dl class="dl-horizontal">
        <dt>
            Độc giả
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocGia.TenDG)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayMuon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayMuon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TienPhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TienPhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu)
        </dd>


    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color d-flex justify-content-center align-items-center">
            <input type="submit" value="Xóa" class="btn btn-delete" /> |
            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-back" })
        </div>
    }
</div>

Project_63131717/Areas/Admin_63131717/Views/QLPhieuMuon_63131717/Edit.cshtml
@model Project_63131717.Models.PhieuMuon

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin_63131717/Views/Shared/PageAdmin.cshtml";
}


<style>
    body {
        background: #f5e7e7
    }

    a {
        text-decoration: none
    }
    /* Định dạng tổng thể cho form */
    .form-horizontal {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    /* Định dạng cho tiêu đề */
    h4 {
        text-align: center;
        font-weight: 700;
    }

    /* Định dạng cho nhãn và input */
    .form-group {
        margin-bottom: 20px;
    }

    .control-label {
        font-weight: bold;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    /* Định dạng cho nút Lưu */
    input[type="submit"], .submit a {
        background-color: #3498db;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        input[type="submit"]:hover, .submit a:hover {
            background-color: #2575b7;
        }

    /* Định dạng cho thông báo lỗi */
    .text-danger {
        color: #ff6347;
    }

    input, textarea {
        margin: 10px 0;
    }

    textarea {
        width: 100%;
        height: 120px;
    }
</style>

@*<script type="text/javascript">
        $(function () {
            $('#NgayTraThucTe').datepicker();
        })
    </script>*@




@using (Html.BeginForm(Html.BeginForm("Edit", "QLPhieuMuon_63131717", FormMethod.Post)))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4 class="text-center text-uppercase" style="color:blue">thông tin phiếu mượn</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IDPM)

    <div class="form-group">
        @Html.LabelFor(model => model.IDDG, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.IDDG, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
            @Html.ValidationMessageFor(model => model.IDDG, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DocGia.TenDG,"Tên độc giả", htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.DocGia.TenDG, new { htmlAttributes = new { @class = "form-control", @readonly = "true"   } })
            @Html.ValidationMessageFor(model => model.DocGia.TenDG, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayMuon, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.NgayMuon, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
            @Html.ValidationMessageFor(model => model.NgayMuon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayTra, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.NgayTra, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
            @Html.ValidationMessageFor(model => model.NgayTra, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TienPhat, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.TienPhat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TienPhat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.TextAreaFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group submit">
        <div class="col-md-offset-2 col-md-12 d-flex justify-content-around align-items-center">
            <input style="margin:0;" type="submit" value="Lưu thay đổi" class="btn btn-default" />
            @Html.ActionLink("Quay lại", "Index")
        </div>
    </div>
</div>
}

Project_63131717/Areas/Admin_63131717/Views/QLPhieuMuon_63131717/Index.cshtml
@model PagedList.IPagedList<Project_63131717.Models.PhieuMuon>
@using PagedList.Mvc



@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin_63131717/Views/Shared/PageAdmin.cshtml";
    var i = 0;
}
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
    a {
        text-decoration: none;
        color: black
    }
</style>
<div class="pb-4 d-flex align-items-center">
    <h2 style="font-family:Arial, Helvetica, sans-serif;font-weight:600;color:#413939;margin:0;">PHIẾU MƯỢN</h2>
</div>

<table class="table table-striped-columns">
    <tr style="background: #f8eeee">
        <th>
            STT
        </th>
        <th>
            ID phiếu mượn
        </th>
        <th>
            ID độc giả
        </th>
        <th>
            Tên độc giả
        </th>
        <th>
            Ngày mượn
        </th>
        <th>
            Ngày trả
        </th>
        <th>
            Tiền phạt 
        </th>
        <th>
            Ghi chú
        </th>

        <th class="text-center">
            Chức năng
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{
                    i = i + 1;
                }
                @i
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDPM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDDG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DocGia.TenDG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayMuon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayTra)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TienPhat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GhiChu)
            </td>
            <td class="text-center">
                @Html.ActionLink("Gia hạn", "Edit", new { id = item.IDPM }) |
                @Html.ActionLink("Phạt", "Phat", new { id = item.IDPM }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.IDPM })
            </td>
        </tr>
    }

</table>
<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>

Project_63131717/Areas/Admin_63131717/Views/QLPhieuMuon_63131717/Phat.cshtml
@model Project_63131717.Models.PhieuMuon

@{
    ViewBag.Title = "Phat";
    Layout = "~/Areas/Admin_63131717/Views/Shared/PageAdmin.cshtml";
}


<style>
    body {
        background: #f5e7e7
    }

    a {
        text-decoration: none
    }
    /* Định dạng tổng thể cho form */
    .form-horizontal {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        background-color: #f9f9f9;
    }

    /* Định dạng cho tiêu đề */
    h4 {
        text-align: center;
        font-weight: 700;
    }

    /* Định dạng cho nhãn và input */
    .form-group {
        margin-bottom: 20px;
    }

    .control-label {
        font-weight: bold;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    /* Định dạng cho nút Lưu */
    input[type="submit"], .submit a {
        background-color: #3498db;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        input[type="submit"]:hover, .submit a:hover {
            background-color: #2575b7;
        }

    /* Định dạng cho thông báo lỗi */
    .text-danger {
        color: #ff6347;
    }

    input, textarea {
        margin: 10px 0;
    }

    textarea {
        width: 100%;
        height: 120px;
    }
</style>

@*<script type="text/javascript">
        $(function () {
            $('#NgayTraThucTe').datepicker();
        })
    </script>*@




@using (Html.BeginForm(Html.BeginForm("Edit", "QLPhieuMuon_63131717", FormMethod.Post)))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4 class="text-center text-uppercase" style="color:blue">Phiếu phạt độc giả</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IDPM)

    <div class="form-group">
        @Html.LabelFor(model => model.IDPM, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.IDPM, new { htmlAttributes = new { @readonly = "true", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IDPM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IDDG, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.IDDG, new { htmlAttributes = new { @readonly = "true", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IDDG, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DocGia.TenDG, "Độc giả", htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.DocGia.TenDG, new { htmlAttributes = new { @readonly = "true", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DocGia.TenDG, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayMuon, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.NgayMuon, new { htmlAttributes = new { @readonly = "true", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayMuon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayTra, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.NgayTra, new { htmlAttributes = new { @readonly = "true", @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgayTra, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TienPhat, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.TienPhat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TienPhat, "Cập nhật số tiền phạt về 0 khi độc giả đã trả tiền !", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-5" })
        <div class="col-md-12">
            @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GhiChu, "Ghi lại số tiền phạt mà độc giả đã trả và lý do phạt!", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group submit">
        <div class="col-md-offset-2 col-md-12 d-flex justify-content-around align-items-center">
            <input style="margin:0;" type="submit" value="Lưu thay đổi" class="btn btn-default" />
            @Html.ActionLink("Quay lại", "Index")
        </div>
    </div>
</div>
}