Project_63131717/Controllers/ListBook_63131717Controller.cs
using PagedList;
using Project_63131717.Models;
using Project_63131717.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Project_63131717.Controllers
{
    public class ListBook_63131717Controller : CheckLogin_63131717Controller
    {
        Project_63131717Entities db = new Project_63131717Entities();
        private const int PageSize = 9;
        // GET: ListBook_63131717
        public ActionResult Index(string tenSach, int? page)
        {
            var sach = db.Saches.ToList();
            if (!string.IsNullOrEmpty(tenSach))
            {
                sach = sach.Where(s => s.TenSach.Contains(tenSach)).ToList();
                ViewBag.tenSach = tenSach;
            }
            int pageNumber = (page ?? 1);
            return View(sach.ToPagedList(pageNumber, PageSize));
        }
        public ActionResult SachTheoTheLoai(string tenTheLoai, int? page)
        {
            var sachTheoTheLoai = db.Saches.Where(s => s.TheLoai.TenTheLoai == tenTheLoai).ToList();
            ViewBag.TenTheLoai = tenTheLoai;
            int pageNumber = (page ?? 1);
            return View(sachTheoTheLoai.ToPagedList(pageNumber, PageSize));
        }
        public ActionResult HienThi(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sach = db.Saches.Find(id);

            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }
    }
}

Project_63131717/Controllers/TraCuuPhieuMuon_63131717Controller.cs
using Project_63131717.Models;
using Project_63131717.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Project_63131717.Controllers
{
    public class TraCuuPhieuMuon_63131717Controller : CheckLogin_63131717Controller
    {
        // GET: TraCuuPhieuMuon_63131717
        Project_63131717Entities db = new Project_63131717Entities();
        // GET: TraCuuPhieuMuon
        private const int pageSize = 10;
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            string username = Session["NameUser"] as string;
            var docGia = db.DocGias.FirstOrDefault(dg => dg.NameUser == username);
            var phieuMuon = db.CT_PM.Where(pm => pm.IDDG == docGia.IDDG).ToList();
            return View(phieuMuon.ToPagedList(pageNumber,pageSize));
        }
    }
}

Project_63131717/Views/Shared/LayoutUser2.cshtml
<!DOCTYPE html>
@{
    var user = HttpContext.Current.Session["NameUser"].ToString();
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Areas/Admin_63131717/Content/admin.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


</head>
<body style="background: #f9fafa">

    <div class="header">
        <div id="body-pd">
            <header class="header" id="header">
                <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
                @* <a style="text-decoration:none;color:black" href="#"><i class="bx bx-user nav-icon" style="margin-right:5px"></i>@user</a>*@
                <div class="user-menu">
                    <div class="dropdown">
                        <button class="dropbtn"><a style="text-decoration:none;color:black" href="#"><i class="bx bx-user nav-icon" style="margin-right:5px"></i>@user</a></button>
                        <div class="dropdown-content">
                            <a href="#">Profile</a>
                            <a href="~/Login_63131717/LogOut">Log out</a>
                        </div>
                    </div>
                </div>

            </header>
            <div class="l-navbar" id="nav-bar" style="background:#0e0c0c">
                <nav class="nav">
                    <div>
                        <a href="#" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">LIBRARY BOOK</span> </a>
                        <div class="nav_list">
                            <a href="~/ListBook_63131717/Index" class="nav_link active"> <i class='bx bx-book-open nav_icon'></i> <span class="nav_name">Danh sách các sách</span> </a>
                            <a href="~/TraCuuPhieuMuon_63131717/Index" class="nav_link"> <i class='bx bx-user nav_icon'></i> <span class="nav_name">Phiếu mượn sách</span> </a>
                            <a href="~/GioSach_63131717/Show" class="nav_link"> <i class='bx bx-shopping-bag'></i> <span class="nav_name">Giỏ hàng</span> </a>

                        </div>
                    </div> <a href="~/Login_63131717/LogOut" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">Log Out</span> </a>
                </nav>
            </div>
        </div>
    </div>
    <div class="content" style="margin-top:80px">
        @RenderBody()
    </div>
    <footer class="footer_section mt-5">
        <hr />
        <div class="container text-center m-3">
            <p>
                &copy; <span id="displayYear"></span> All Rights Reserved 2023

            </p>
        </div>
    </footer>
    <script src="~/Areas/Admin_63131717/Content/admin.js"></script>
</body>

</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

Project_63131717/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    
        <meta name="viewport" content="width=device-width" />
        <meta charset="UTF-8">
        <title>@ViewBag.Title</title>
        <link href="~/Content/StyleHome.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    
    </head>
    
<body>
    <header>
        <div class="banner">
            <img style="width:100%;height:15vh" src="~/Content/image/panner.jpg" alt="banner" />
        </div>
        <div class="topnav" id="myTopnav" style="background: #4856c4 ">
            <a href="">Logo</a>
            <a href="@Url.Action("Index","ListBook_63131717")">Danh sách các sách</a>
            <a href="@Url.Action("Index","TraCuuPhieuMuon_63131717")">Tra cứu phiếu mượn</a>
            <a style="float:right;align-items:center;" href="~/Login_63131717/LogOutUser">Log Out</a>
        </div>
    </header>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>